version: '3.2'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - .:/application
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD='~xn*Kv!2pc{TY!tV'
      - MYSQL_DATABASE=arishtidb
      - MYSQL_USER=root
      - MYSQL_PASSW0RD='~xn*Kv!2pc{TY!tV'
  website:
    container_name: phpCode
    image: php:7.3-apache
    build:
      context: ./
    volumes:
      - ./:/var/www/html
    ports:
      - 1337:80
    depends_on:
      - mysql